### PR TITLE
Upgrade to GCC 3.2.3

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by sp193** [comment]
What are the benefits of this upgrade, other than the fact that it's a (slightly) newer version of GCC? My concern is that your work is relatively untested, compared to the current GCC v3.2.2 toolchain.

**Comment by uyjulian** [comment]
The patch is cleaned up, and GCC is upgraded to v3.2.3
Also, there are additional patch to allow compilation on Clang more easily.

**Comment by sp193** [comment]
I'm quite sure that the other developers here can see the pull request, but have just not replied. I'm not sure if I am in the right position to just accept your merge request.
If I asked you whether you have confidence that your work here will work properly, can you confidently say "yes"? I won't blame you if anything goes wrong, but I just cannot help you with fixing issues with GCC because it's really out of my league.

**Comment by uyjulian** [comment]
The patch is VERY OLD code, I wouldn't expect it to work 100% on modern systems (same with the one already in git)

**Comment by sp193** [comment]
I see. We'll see how this goes then.

**Comment by sp193** [comment]
It appears that your toolchain is attempting to build collect2, but that doesn't work on MinGW. Do you have a solution to that?

**Comment by uyjulian** [comment]
What do you mean "doesn't work on MinGW"?
Explain further, please.

**Comment by sp193** [comment]
It appears that some system functions like fork() aren't implemented properly on MinGW, but the old toolchain doesn't have such an issue.
There are some comments on this matter over here: http://psx-scene.com/forums/f150/windows-opl-compiling-guide-114892/index19.html
I don't personally know what happens because I've stopped using MinGW since 2013 or so.

**Pull request merged**
