### PR TITLE
Docker clouds initializing

### PR DESCRIPTION
**Pull request by AKuHAK**
Ok guys, I decided to make this 2 pull request and explain what is goal of this project.

I created automated builds for Docker image. Few words about Docker engine: In a nutshell this is something like preinstalled system which will contain fully configured toolchain for our work. It is easy to grab docker image and deploy it into machine without need to install all dependencies and specific versions of some tools. Just download image and "mount" it. These images are also very useful for testing things.

But what is difference from [this project](https://github.com/mlafeldt/docker-ps2dev) maintained by @mlafeldt .
1) It will be up-to-date!!! For now docker image is updated only when docker image maintainer runs update manually. But with automated build help it will build new image every time new commit is pushed into main repository.
2) We will get rid of not necessary third-party repository, so every "docker-image" repo became deprecated and can be easily removed. It is better to keep all things inside ps2dev organization to my mind.
3) It is possible to use same docker file for different branches without need to specify branch info inside Dockerfile.
4) Now it is possible to keep integrating docker into other ps2dev projects cause I keep only toolchain side and removed all stuff that is dependent.
Maybe it is not really clear why I removed such things like ps2-packer, gsKit, ps2eth, ... it even ps2sdk. The answer is cause it is not possible at this moment keep all these libraries updated. But! But specially for this I created another pull request at ps2sdk repository.

[PS2SDK's pull request](https://github.com/ps2dev/ps2sdk/pull/56) is another docker image which is BASED ON this one created in ps2toolchain repository. So Dockerimage in ps2sdk repo will contain ps2toolchain + ps2sdk. And this second Dockerimage will be updated every time some commit is pushed into ps2sdk github repository AND every time some commit is pushed into ps2toolchain repository.

But to make things working I need that somebody with write access into ps2dev team accepted my changes in docker infrastructure.
I created [ps2dev organization](https://cloud.docker.com/app/ps2dev) in docker clouds and granted write access to @mlafeldt because he is only one from ps2dev team who is registered at docker.com. Maybe @mlafeldt or @sp193 can accept my changes at docker infrastructure? (@sp193 need to tell me his username on docker.com so I can add them into admin group)
Here is step-by-step guide:
- Go to [https://cloud.docker.com/app/ps2dev/settings#container-source-providers](https://cloud.docker.com/app/ps2dev/settings#container-source-providers) and Connect github provider.
- Go to [https://github.com/settings/applications](https://github.com/settings/applications), click on Docker Cloud Builder and grant access for ps2dev organization.
- Go to [https://github.com/settings/applications](https://github.com/settings/applications), click on Docker Hub Registry (if exist) and grant access for ps2dev organization.
- Go to [https://cloud.docker.com/app/ps2dev/repository/docker/ps2dev/ps2toolchain/builds/edit](https://cloud.docker.com/app/ps2dev/repository/docker/ps2dev/ps2toolchain/builds/edit) and select source repository ps2dev organization and ps2toolchain repo. Keep build rules default to simplify developing!!!
Repeat last step for ps2sdk and you can accept my pull requests :)

My goal is to add docker into all repo to keep things updated and simplify developing.

### CODE REVIEW

**Comment by AKuHAK** [comment]
Bump. Added [ps2-packer](https://github.com/ps2dev/ps2-packer/pull/12) as next Dockerimage step. @sp193

**Comment by sp193** [comment]
@mlafeldt may be a better person to ask for this, since he's got the "owner" permissions over these repositories and is already doing something similar.

**Comment by AKuHAK** [comment]
@sp193 it seems that there is no other active developers. Travis system keeps failing in uLaunchELF project cause of very long compilation process. AutoDocker initialization can solve this problem. I still hope that someday it will be integrated into official repo :)

**Comment by sp193** [comment]
Hi,
Okay, I'll try to do what you have suggested above, after my finals (~10 May), since I have to start focusing on studies now. If I can make the necessary changes with my allocated priviledges, then that will be great for everyone, I guess.

But thanks for trying to make the PS2 world work great, either way.

**Comment by sp193** [comment]
So to confirm what I have to do now:
1. Create an account on docker.com.
2. Give you my ID, so that you can add me into the ps2dev group.
3. Follow the steps that you mentioned in the description of this pull request.
4. Accept pull request (for ps2toolchain, ps2sdk and so on)

**Comment by AKuHAK** [comment]
Yes!! Thank you for your effort!!

**Comment by sp193** [comment]
Now here's the issue, which might be due to me not having the necessary permissions: I cannot select the source repository for ps2toolchain (I don't have the option for ps2dev, at all). :|

**Comment by AKuHAK** [comment]
Thank you )) at least you tried

**Comment by rickgaiser** [comment]
I'm closing this old issue as we're now able to do the same using github actions, and we no longer need the missing travis-ci permissions. A Dockerfile still needs to be added though. However, I would prefer the dockerfile to use alpine instead of ubuntu, becouse it's much smaller.

**Pull request closed without merging**
