### PR TITLE
Update Newlib to 2.2.0

### PR DESCRIPTION
**Pull request by uyjulian**
I got updates for binutils and gcc on the way, but newlib was a simple update, so I guess I'll just do that first.

### CODE REVIEW

**Comment by sp193** [comment]
We can compile v2.20 without running into ICEs? O_O
Well, that's great!

**Comment by daf0x** [comment]
No, not as far as I can tell. First of all, the current GCC version (3.2.3) does not cleanly compile stage1. Even if you fix that, there are some compile errors in NewLib. If you fix those, you will see that the ICE is still present. I think you need at least GCC 3.3.1 to fix that. Alternatively, you can disable "double complex" support in NewLib. This allows you to get as far as GCC's stage3, but this time it will fail somewhere in libiberty (it complains about mismatched prototypes for 'psignal').

I have the fixes that will get you as far as that in my fork, but before you simply apply those, I'd like to know where you are going with this. Updating NewLib is nice and all, but you're trying to compile a library released last December (6 months ago) with a 12 YEAR old compiler... Further, looking at uyjulian's repository, it appears that he is now working on GCC 4.9.2?!

So before any further attempt is made to try to get the current state of the repository _compiling_ (note: not necessarily working!), I'd like to know how your road map looks like at present?

**Comment by uyjulian** [comment]
I'm currently getting ps2sdk fixed to be able to be conpiled with GCC 5.1
Also, I meant to put in a PR to revert this pull request, but never did...

**Comment by sp193** [comment]
@daf0x, on my end, there is no roadmap for these tools. There aren't really any newer versions of the tools that will support the PS2 fully and properly.
@uyjulian is working on porting newer tools (GCC + binutils for only the IOP) over... but unless he learns how to add the missing features for the R5900 support within GCC, you probably won't see a full update of the PS2 toolchain to stuff from 2015. :/
Plus I am still unsure of whether I should fully support the idea of the porting of a new version of GCC for the IOP. As observed before in my own port of GCC v4.9.2, there are issues with using a newer version of GCC, due to differences between GCC 3 and 4. Basically nearly every piece of PS2 software out there (plus the libraries in the PS2SDK) will have to be rewritten to compile properly with the new version of GCC.
But if it all turns out well... I'm all for it.

**Comment by sp193** [comment]
It's beyond my own personal capabilities to add the following features to the official support for the R5900 within GCC, which are just the obvious features that are still missing:
1. Support for the R5900 MMI instructions.
2. Enabling of the 2nd pipeline.
3. For number 2, support for the EE FPU registers (ACC etc).

**Pull request merged**
